C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     (1*(1/(1+(- 2*MNul**2 - 2*P(-1,1)*P(-1,2))/dval)))*Gamma(3,2,1)
C     
      SUBROUTINE FF1P0_3(F1, F2, COUP, M3, W3,V3)
      IMPLICIT NONE
      INCLUDE '../MODEL/input.inc'
      INCLUDE '../MODEL/coupl.inc'
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 F2(*)
      COMPLEX*16 COUP
      COMPLEX*16 TMP1
      REAL*8 P1(0:3)
      REAL*8 W3
      REAL*8 P2(0:3)
      REAL*8 P3(0:3)
      REAL*8 M3
      COMPLEX*16 F1(*)
      COMPLEX*16 DENOM
      COMPLEX*16 V3(6)
      COMPLEX*16 FCT2
      COMPLEX*16 FCT1
      COMPLEX*16 FCT0
      P1(0) = DBLE(F1(1))
      P1(1) = DBLE(F1(2))
      P1(2) = DIMAG(F1(2))
      P1(3) = DIMAG(F1(1))
      P2(0) = DBLE(F2(1))
      P2(1) = DBLE(F2(2))
      P2(2) = DIMAG(F2(2))
      P2(3) = DIMAG(F2(1))
      V3(1) = +F1(1)+F2(1)
      V3(2) = +F1(2)+F2(2)
      P3(0) = -DBLE(V3(1))
      P3(1) = -DBLE(V3(2))
      P3(2) = -DIMAG(V3(2))
      P3(3) = -DIMAG(V3(1))
      TMP1 = (P1(0)*P2(0)-P1(1)*P2(1)-P1(2)*P2(2)-P1(3)*P2(3))
      FCT0 = (MDL_MNUL)**(2D0)
      FCT1 = 1D0/(MDL_DVAL)
      FCT2 = 1D0/((-2D0)*(FCT1*(FCT0+TMP1)+ -1D0/2D0))
      DENOM = COUP/(P3(0)**2-P3(1)**2-P3(2)**2-P3(3)**2 - M3 * (M3 -CI
     $ * W3))
      V3(3)= DENOM*(-CI )* FCT2*(F1(3)*F2(5)+F1(4)*F2(6)+F1(5)*F2(3)
     $ +F1(6)*F2(4))
      V3(4)= DENOM*(-CI )* FCT2*(F1(5)*F2(4)+F1(6)*F2(3)-F1(3)*F2(6)
     $ -F1(4)*F2(5))
      V3(5)= DENOM*(-CI )* FCT2*(-CI*(F1(3)*F2(6)+F1(6)*F2(3))+CI
     $ *(F1(4)*F2(5)+F1(5)*F2(4)))
      V3(6)= DENOM*(-CI )* FCT2*(F1(4)*F2(6)+F1(5)*F2(3)-F1(3)*F2(5)
     $ -F1(6)*F2(4))
      END


